### ISSUE TITLE
Mget should be on this wikipedia table

### ISSUE THREAD

**Issue by zoobab** [rockdaboot/mget#30]
Mget should be on this wikipedia table:

https://en.wikipedia.org/wiki/Metalink

**Comment by rockdaboot** [comment]
Thanks for pointing out !
I never edited Wikipedia articles... If you like to do so, I would appreciate it (and feel free to ask me questions if something is unclear).

**Comment by rockdaboot** [comment]
I just put it there.

**Comment by rockdaboot** [comment]
They banned me for promoting this project.
Could anybody else edit the Wikipedia page, please !

**Comment by juaristi** [comment]
Really? How weird...

I'll try it myself in a while... 

---- Tim Rühsen escribió ----

**Comment by rockdaboot** [comment]
Please wait until I talked further with them. You can follow the discussion here
https://en.wikipedia.org/wiki/User_talk:Rockdaboot
(I said 'banned', but they call it 'unlimited block').

**Comment by rockdaboot** [comment]
People, please *don't* edit the Wikipedia page. 
And they will block your account *indefinitely* as they did with mine.

I leave this issue open as a warning.
